### ISSUE TITLE
Infinite loop during packing

### ISSUE THREAD

**Issue by hasanbalci** [iVis-at-Bilkent/cytoscape.js-layout-utilities#11]
I was trying to pack two disconnected nodes and realized that sometimes code runs into infinite loop. I think it's [this loop](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/bf1d73958336bb348cea3f179bf843f82b29938b/src/core/layout-utilities.js#L506) in which the `cells` variable becomes 0 and cannot find placement. A sample case can be found [here](https://jsfiddle.net/4dxufLwt/).

**Comment by ugurdogrusoz** [comment]
@hasanbalci Pls check

**Comment by hasanbalci** [comment]
In this [sample case](https://jsfiddle.net/v6yhetob/29/), I give the positions of edge's source and target nodes as the edge start and end points instead of using edge's bounding box since it's more convenient in my case. Packing either takes too much time or runs into infinite loop and I think it sticks around on [this for loop](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/000cb6b382c1934a784187a2c6004f0a26e7e200/src/core/general-utils.js#L24).

**Comment by hasanbalci** [comment]
It's working now.
