### ISSUE TITLE
packingApi.packComponents() hangs sometimes 1.0.0

### ISSUE THREAD

**Issue by pkovanen** [iVis-at-Bilkent/cytoscape.js-layout-utilities#12]
Our application sometimes hangs, and I've now spent several hours tracking down where the problem is.

Finally I found out, that the problem is with packComponents() method.

If I have to nodes, sometimes the following subgraphs are generated and this results in busy loop:

```
[
    {
        "nodes": [
            {
                "x": 0,
                "y": 0,
                "width": 45,
                "height": 45
            }
        ],
        "edges": []
    },
    {
        "nodes": [
            {
                "x": 55,
                "y": 0,
                "width": 45,
                "height": 45
            }
        ],
        "edges": []
    }
]
```

Below you can see the whole code:

```
    let cy = cytoscape({
      container: this.$refs.cyto,
      elements: this.generateElements(), 
      style: this.generateStyle(),
      autounselectify: true,
      userPanningEnabled: false,
      userZoomingEnabled: false,
      boxSelectionEnabled: false,
      autoungrabify: true
    });

    cyInstance = cy;

    cy.layout({
      name: "cose-bilkent",
      animate: false,
      idealEdgeLength: 20,
      quality: "proof",
      randomize: false,
      nodeDimensionsIncludeLabels: true,
      nodeRepulsion: 8000,
      edgeElasticity: 0.7,
      nestingFactor: 0.1,
      numIter: 10000,
      gravity: 0.25
    }).run();

    var packingApi = cy.layoutUtilities({
      desiredAspectRatio: 1,
      polyominoGridSizeFactor: 1,
      utilityFunction: 1,
      componentSpacing: 0
    });

    var components = cy.elements(":visible").components();
    var subgraphs = [];
    components.forEach(function(component) {
      var subgraph = {};
      subgraph.nodes = [];
      subgraph.edges = [];

      component.edges().forEach(function(edge) {
        var boundingBox = edge.boundingBox();
        subgraph.edges.push({
          startX: boundingBox.x1,
          startY: boundingBox.y1,
          endX: boundingBox.x2,
          endY: boundingBox.y2
        });
      });
      component.nodes().forEach(function(node) {
        var boundingBox = node.boundingBox();
        subgraph.nodes.push({
          x: boundingBox.x1,
          y: boundingBox.y1,
          width: boundingBox.w,
          height: boundingBox.h
        });
      });

      subgraphs.push(subgraph);
    });

    var result = packingApi.packComponents(subgraphs);

```

Let me know if you think the problem could be caused with our generateElements() or generateStyles() methods, I can then try and tidy them up. However they are quite simple methods and I think are not part of the problem.

**Comment by nasimsaleh** [comment]
@pkovanen  I ran `packComponents()` with your given input data with only two nodes, and it seemed to work fine. I  first defined:
`var subgraphs = [
    {
        "nodes": [
            {
                "x": 0,
                "y": 0,
                "width": 45,
                "height": 45
            }
        ],
        "edges": []
    },
    {
        "nodes": [
            {
                "x": 55,
                "y": 0,
                "width": 45,
                "height": 45
            }
        ],
        "edges": []
    }
]` 
then call the packing function:
`packingApi.packComponents(subgraphs)`

Let me know if can find an example I can recreate.

**Comment by nasimsaleh** [comment]
@pkovanen I am closing this issue, if you have any further questions, we can reopen.

**Comment by hasanbalci** [comment]
I tried it with the subgraphs: 
`var subgraphs = [ { "nodes": [ { "x": 0, "y": 0, "width": 32, "height": 32 } ], "edges": [] }, { "nodes": [ { "x": 42, "y": 0, "width": 32, "height": 32 } ], "edges": [] } ];`
and it gets stuck around [here](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/blob/000cb6b382c1934a784187a2c6004f0a26e7e200/src/core/polyomino-packing.js#L68).

**Comment by nasimsaleh** [comment]
@hasanbalci @pkovanen I was testing it on the unstable branch, in master branch the issue exists. [This related issue](https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/issues/11) was reported and fixed in unstable branch and it will be available in next release.
