### ISSUE TITLE
Master branch ahead of unstable

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#13]
Let's make sure unstable has all changes in the master branch.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz Its not ahead. Unstable has all the master commits except for readme and package.json file.  Unstable is ahead, because it has a bug fix. When we release readme and package.json will be reviewed.

**Comment by ugurdogrusoz** [comment]
Why not update readme now to synch?

**Comment by nasimsaleh** [comment]
@ugurdogrusoz I merged master into unstable. now unstable has all commits in master.
