### ISSUE TITLE
Change default value for component spacing in packing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#15]
Let's change 'componentSpacing' default from 0 to 30. Using no spacing between components makes it very difficult to distinguish components.

**Comment by ugurdogrusoz** [comment]
Pls check and close if OK

**Comment by hasanbalci** [comment]
@canbax It seems ok, but let's also change the 'componentSpacing' default from 0 to 30 in the demo.
