### ISSUE TITLE
Packing moves components to unrelated location

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#18]
When the utility of packing of components is used for disconnected graphs, the components may end up in locations which are completely different than their original ones.
Instead, we should compute the center of a minimal bounding box based on input positions and adjust the output to be centered at this location as well.

**Comment by onsah** [comment]
Since PR #19 is merged, I think this issue can be closed.

**Comment by ugurdogrusoz** [comment]
When we apply incremental packing with the new implementation, we have the same problem. The drawing drifts away. Ideally, the center of the drawing should be the same as the previous one after an incremental layout.

**Comment by ugurdogrusoz** [comment]
Great thanks @hasanbalci
