### ISSUE TITLE
Pack components inconsistent spacing

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#25]
With the component spacing of 30, incremental and non-incremental layout results in different actual spacing:

Non-incremental:
![Screenshot 2021-02-24 162123](https://user-images.githubusercontent.com/3874988/109006717-6a0b8080-76bc-11eb-88a2-fc2d1e5dcdad.png)

Incremental:
![Screenshot 2021-02-24 162139](https://user-images.githubusercontent.com/3874988/109006706-68da5380-76bc-11eb-9bb9-652ff2be91dc.png)

Let's make them consistent (by trimming values prior to the operations if needed). I think the default should be 80 and the non-incremental version should deduct a constant amount from this value to stay consistent.

**Comment by hasanbalci** [comment]
Done with this commit 446d0a66d83358b378330d5e5f767c10fa97b89d.

**Comment by ugurdogrusoz** [comment]
Looks good. The only problem is in the demo. When the spacing is given as 0 or below, incremental packing will do nothing!

**Comment by hasanbalci** [comment]
It should be solved now.
