### ISSUE TITLE
Update Demo and README

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#28]
We should illustrate how new nodes (neighbors of existing ones) can be initially nicely placed before an incremental layout can take place (`placeNewNodes`) in the Demo as well (maybe something similar to how we do it in CiSE demo when right clicked on a node).
In addition, README should be improved and all features should be properly documented.

**Comment by hasanbalci** [comment]
9f092e24e6cf73aff5ad67861eeb5cc465468029 updates demo to illustrate the placement of newly added nodes. README is also updated to reflect changes especially related to incremental packing.
