### ISSUE TITLE
Demo improvements

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#4]
- [x] 1. "Desired Aspect Ratio" => "Desired aspect ratio" and so on everywhere including dropdown box content (only capitalize the first word)
- [x] 2. Move Result aspect ratio and Result fullness in "Pack components" section
- [x] 3. Make the step increment/decrement 0.1 for Polyomino grid size factor as well
- [x] 4. Display results only 2 digits after decimal point
- [x] 5. Doesn't look like Result aspect ratio is calculated (taken from?) correctly as it's almost always the same as Desired aspect ratio
- [x] 6. Relabel nodes consistently n1, n2, ...
- [x] 7. Also display "Result adjusted fullness".

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  The result of the aspect Ratio changes, in many cases it is equal to the desired aspect ratio.

**Comment by ugurdogrusoz** [comment]
Let's make the increment step for grid size factor 0.05. Let's also display Result adjusted fullness as a stat.
