### ISSUE TITLE
Search for more levels before a decision

### ISSUE THREAD

**Issue by ugurdogrusoz** [iVis-at-Bilkent/cytoscape.js-layout-utilities#6]
Looks like we should try more neighboring levels for a good location to place the next polyomino before we make a decision. Otherwise, this is more or less the first closest place that works. Maybe at least maximum of half of width and height (# of squares) of the bounding box of the polyomino.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  I already pushed it before seeing the created issue here.
https://github.com/iVis-at-Bilkent/cytoscape.js-layout-utilities/commit/43916e1a4f431fbd6bea5b811b27d455f8afb929

**Comment by ugurdogrusoz** [comment]
Works nicely. One more improvement could be as follows. Among all those locations yielding the same *adjusted fullness*, looks like we're settling for an arbitrary one. Shouldn't we settle for the one yielding the biggest *fullness*?
For example same graph with d.a.r. of 1.25:
<img width="381" alt="125" src="https://user-images.githubusercontent.com/3874988/64129904-a9a72400-cdc7-11e9-8416-1b07931e7b39.png">

vs. d.a.r. of 1.50:
<img width="433" alt="150" src="https://user-images.githubusercontent.com/3874988/64129911-b3308c00-cdc7-11e9-9c98-207f7fa8bb5d.png">

With the latter, we're wasting space unnecessarily, as the former clearly shows that there is a better packing with the same adjusted fullness.

**Comment by nasimsaleh** [comment]
@ugurdogrusoz  Now it is changed to look first at Adjusted Fullness, and if equal then Fullness and finally to the closer aspect ratio. However, the result might not change because in the example above the desired aspect ratio is different so the adjusted fullness will also be different because adjusted fullness = f(d.a.r)
