### ISSUE TITLE
Show all bug for hidden edges

### ISSUE THREAD

**Issue by PermanAtayev** [iVis-at-Bilkent/cytoscape.js-layout-utilities#7]
If you hide edges in the demo and try to make them reapper by clicking "show all" it doesn't restore them. However, it restores them if you use the "show hidden neighbours" option.

**Comment by ugurdogrusoz** [comment]
Good catch! Show all should show everything.

**Comment by PermanAtayev** [comment]
Now "show all" shows edges as well. But there is a minor thing left.
For example, If I remove an edge that goes from n15 to n17, then remove remove either node n15 or n17 and try to recover it from "show hidden neighbors selected" a neighbor of that node, it will recover the node but it won't update the color:

![image](https://user-images.githubusercontent.com/38570154/64248611-44177c80-cf1a-11e9-8583-41c0bbef3986.png)

**Comment by PermanAtayev** [comment]
I am not exactly sure what triggers this, but here as well I got the same issue, the node that doesn't have any hidden neighbors left is still colored:
![image](https://user-images.githubusercontent.com/38570154/64248864-fd765200-cf1a-11e9-812a-899ccc5b3bdb.

**Comment by ugurdogrusoz** [comment]
@nasimsaleh no big deal if this is difficult to deal with.

**Comment by ugurdogrusoz** [comment]
@PermanAtayev please confirm the fix

**Comment by PermanAtayev** [comment]
It's working, good job:)
